### ISSUE TITLE
Requested changes to Motus R Book

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#941]
We've been accumulating requests for changes to the Motus R Book. I will summarise them here:
* [ ] Explain signal strength vs. time plots (#940)
* [ ] Consistency in variable names (#706) @cjardine-bsc 
* [ ] Dealing with large datasets (#900)
* [ ] Formatting errors (#918)
* [ ] Instructions on how to deal with aliasing (#779). See [Motus Tag Guide](https://docs.motus.org/tagguide/tag-aliasing#identifying-aliased-detections) @leberrigan 
* [ ] Clarify best practices with regards to UTC offset (#834) @leberrigan 
* [x] Clairfy filters (manual vs. noise and `motusFilter()` vs. `filterByActivity()`; #944)
* [ ] Clairfy `tagme(..., forceMeta = TRUE)` vs. `metadata()` and why not all project receivers are in downloaded with tag data (#867)
* [ ] Database diagram of all the r tables and their relationships to one another.
* [ ] explanation of public projects and how to get a list of which projects you have access to

**Comment by adamdsmith** [comment]
Hope this is helpful, but it is admittedly a bit of a brain dump...

Re: signal strength vs. time plots, I do a few things to help with interpretation:

- change the symbology of the points to display generic antenna orientation. Essentially, I assign each antenna a generic orientation into one of four cardinal bins, and attempt to  use a symbol that reflects that orientation: N (up arrow), S (down arrow), E (square), and W (diamond). The E/W options aren't ideal, but they're intuitive enough I think.
- color each symbol by a few bins of runLength (<5; 6-10, 11-20, >20)
- highlight (ring in bold red color) any hits/runs that need my further inspections based on various criteria (in descending order of grievousness: ambiguous tag, high median freqsd, high hourly pulse counts, runLen of 3, flagged by motusFilter, Lotek/CTT: <2 consecutive bursts, SG: <3 consecutive bursts, hit with high freqsd, and excessive burstSlop).

For example:

![image](https://user-images.githubusercontent.com/3195855/113354314-ff79e000-930c-11eb-9921-b46274393cef.png)

**Comment by steffilazerte** [comment]
Should I be the one adding these additions? Or are we going to be divvying up these issues and addressing them separately? 

Somethings might be best explained by people with a better working knowledge of motus tracking data (as opposed to knowledge of the motus R package), but other things I can definitely tackle. 

I think I'm confused right now as to what is expected of me and when.

**Comment by denislepage** [comment]
I don't think we've decided that far, and it isn't yet clear to me either who will be responsible for each for these. Perhaps we need a call dedicated to tackling this and divvying up to conquer. We have our regular call on Thursdays 13h30 EDT. We should have @steffilazerte  join for one of them. I'd be fine with tomorrow. @StuMackenzie do you have other priorities to cover this week?

**Comment by cjardine-bsc** [comment]
Another one is a database diagram of all the r tables and their relationships to one another.

**Comment by steffilazerte** [comment]
I've got the initial Motus R book set up as a pkgdown site. Right now we can access it here: https://motuswts.github.io/motus/articles/index.html

I've made some initial tweaks to the "Chapters" mostly referring to articles instead of book.  

The repository is also set up to automatically re-render the site on each push. I think I should also be able to set it up to work with a beta version as well, but that'll take a bit of tweaking. 

Next I'm working on re-organizing some of the more complex topics into separate articles where they can be better expanded on (i.e. motusFilter, GPS, large data sets etc.).

**Comment by steffilazerte** [comment]
Okay, I've finished the first draft of re-organizing the book into a website and can now start working on the individual additions. 
You can see the current status here: https://motuswts.github.io/motus/dev/articles/index.html (Note the "/dev/" This is is a development website, **not** the public website here: https://motuswts.github.io/motus/)

Notable changes:

- I moved GPS points and Filtering to their own articles
  - These articles are linked to in the main chapters as more advanced topics
  - I removed/pared these sections from the main chapters
- I've clarified `motusFilter`/`filterByActivity()` in the new "In-depth detections filtering" article (Review requested in #981)
- I removed author and revision credits from the main chapters and instead was explicit that the articles are based on the original book, who those authors were, etc. I think it was just too clumsy otherwise
- I took and expanded on the summary section from Chapter 3 and made it into a very brief "Getting Started" article

Next to do:

- Changes summarized in the [first comment](https://github.com/MotusDev/Motus-TO-DO/issues/941#issue-846581128)
- Re-vamp Chapter 6

**QUESTION**:
- Do people mostly work with flat, data frame files? Or are most databases too big for that?
   - Right now, everything in the examples is transformed to flat, and I'll continue to do that, but if most people try to keep their files as data bases, then I'll change the examples to do that, as much as possible.

**Comment by denislepage** [comment]
There are a few different ways by which people will use the data. One of the main limitation of working from the database is that it currently takes a long time, so you would likely want to be able to do this only once. Once you have a dataframe, you can save it as an RDS file, but if you work from a database connection object, you may need to recreate it at each session, and every time you access the database could be quite slow. There may be ways to work around those limitations though that are worth exploring.

In an ideal world, you would only need to convert the data at the very last minute to pass to various R function (plotting, modeling, etc.), many of which won't work with database connection objects.

In reality, the steps to extract the data could be quite slow on a large database, especially if you are relying on the boilerplate alltags view, which probably almost everyone does. The current instructions are to extract all your data, do some basic data modifications (e.g. converting datetime formats) and then change to an RDS file that you can start from in any future iterations. That approach likely breaks down as your database grows, so one possible approach is to reduce the size of the file in smaller chunks until you get rid of the size problem which would likely lead to a fair bit of fiddling.

The solution may also differ depending on whether you are working with a receiver file or a project file. On a receiver file, breaking down the logic by project may work most of the time, but may still break down if you have an extensive dataset with dozens of birds recorded over long periods (e.g. a colony).

If we can find a way to make this efficient enough, it would be easier to advocate for the same approach regardless of the database size. Typically, in the early stages, people will want to look at tags individually, so they'll go through tags one by one, and create plots and outputs that they can examine for outliers (e.g. detections on receivers that are out of range on a project database), or timelines of individual birds with signal strengths on different antennae on a receiver database.

1. get a list of all the tags you want to work with. If you want to limit this to only tags that are in the database, the quickest way is to get this from the runs table. (e.g.``select distinct motusTagID from runs where motusTagID > 0``, or some dplyr equivalent to doing this). That list also doesn't include potential aliases (motusTagID < 0). You can also create a customized list of tags (say only tags for a given species, or tags detected in the past 6 months by subsetting the runs table such as ``select distinct motusTagID from runs where motusTagID > 0 and tsBegin > (julianday('now') - 180 - 2440587.5)*86400.0; ``).

2. create a loop on the tag list, and pull only the detection data relevant for a single tag at each step. Building queries that only read from the needed tables is going to be much more efficient than the view. But the biggest gain in query speed may come from proper indexing. I did investigate this earlier, but didn't see a major impact. I may have had a breakthrough though (example using a 250MB database with 8 tags). The query to extract the data should likely be as specific as possible and use only the necessary fields:

``` 

-- no index, alltags view: 3180 ms
select max(ts) from alltags a where motusTagId = 10696

-- no index, table join: 2930 ms
select max(ts) from runs a inner join hits b on a.runID = b.runID  where motusTagId = 10696

-- adding indexes
create index ix_runs_motusTagID  on runs (motusTagID, runID);
create index ix_hits_runID on hits (runID, ts);

-- indexes, alltags view: 2401 ms
select max(ts) from alltags a where motusTagId = 10696

-- indexes, table joins: 4 ms
select max(ts) from runs a inner join hits b on a.runID = b.runID  where motusTagId = 10696;

-- drop indexes
drop index ix_runs_motusTagID ;
drop index ix_hits_runID ;

```
The most appropriate indexes will be very query dependent. The gain on the alltags view is relatively modest, because that view tries to do many different types of joins, but it is substantial when querying only the 2 tables (runs and hits), and it will likely be worth trying to create more specific views that are well optimized for their needs. It's probably worth including some details on the value of indexing for people trying to create their own custom joins and filtering, but I would make sure the ones we want (such as those above) are already in the database by default.

Given the above, creating a dataframe that only gets hits for 1 tag would be quite efficient, and could be placed in a loop.

3. Once you have a small enough dataframe, you can then create the plots and visualizations that you need, export them to a folder, and continue looping. From that exercise, you would build a list of valid runs to include or invalid runs to exclude for instance, or a list of the combinations of tagID's and receiver ID's that you want to work with. Saving that list of runs or tag+receiver ID'S as an RDS is potentially more important than saving the data itself, especially if you can easily extract it again.

The above approach would work well if you want to examine each tag individually, but probably less so if you are trying to combine several tags in the same visualizations. This is potentially where someone could rely only on the runs table, rather than the hits. 

The next section of the chapter could then show an example that pulls the tracks after they have been cleaned up, and builds a track visualization combining multiple tags, for instance. I'm almost certain that this visualization wouldn't need to query the hits table, but I could be wrong.

@ajmacdonald3  and @leberrigan  mentioned today that they have some example code that does things like described above, which they can share.

As I said, my above examples are a bit limited, as they only pull from 2 tables (hits and runs), which potentially leave some important fields out (though those could be merged after the single tag df is created), and they also ignore the issue of aliases.

The above view for tag hits would need to join with the ambigs table as follow to include cases where hits are ambiguous, but this is now again slower than the option that only reads from the 2 tables. This is the approach now taken by alltags.

```
select max(ts) from runs a inner join hits b on a.runID = b.runID
	left join allambigs c  on a.motusTagID = c.ambigID
	where coalesce(c.motusTagID, a.motusTagID) = 10696
```

A faster approach would likely be to get a list of ambigID's that match your tag, and then query the hits table on that basis as follow. This only works well if you are only querying a single tag, or a known set of tags:

```
select ambigID from allambigs where motusTagID = 10696

select max(ts) from runs a inner join hits b on a.runID = b.runID
	where a.motusTagID in (10696, -410, -515, -598)
```
A slightly more generic way to do this, although probably a bit less efficient, is something like this:

```
select * from runs a inner join hits b on a.runID = b.runID
  where motusTagId = 10696
  or motusTagID in (select ambigID from allambigs where motusTagID = 10696);
```

**Comment by ajmacdonald3** [comment]
My sense is that most people work with flat dataframes. As an example, here's some code I used to filter some NJ red knot data. Sorry it's long! There are a few things in there specific to that data, like pulling tags of interest from CSVs of banding data, but the overall process is the method I tend to use for filtering data. I try to do a number of operations to pair the data down to only tags and fields I'm interested in and remove obvious false positives before converting to a flat dataframe to avoid memory issues. I do a number of joins with the various tables after converting them to flat dataframes, maybe it would make more sense to do those prior to converting for larger datasets.

---
title: "NJ motus data"
author: "Amie MacDonald and Ariel Lenske"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Outline

Download data from the NJ REKN motus detection data for tags of interest. Follow these sequential steps:

1. download SQLite `.motus` databases for tags of interest (by project)
2. load the detection data and pull out specific tags
3. do a basic filter of the detection data and make diagnostic maps and signal strength plots for each tag

## Set up

Load required packages and set up environment. Source a script of useful custom functions.

```{r}

# load packages
library(motus)
library(motusData)
library(DBI)
library(RSQLite)
library(tidyverse)
library(dbplyr)
library(lubridate)
library(mapdata)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(viridis)
library(readxl)

# set timezone
Sys.setenv(TZ = "GMT")

# source functions
source("./analysis/useful_functions.R")

# set up basic things for maps (need rgdal package installed) 
theme_set(theme_bw())
world <- ne_countries(scale = "medium", returnclass = "sf") # need rgeos package installed
#lakes <- ne_download(scale = "medium", type = 'lakes', category = 'physical',
#                     returnclass = "sf", destdir = "./map-data/lakes") # only need this first time downloading
lakes <- ne_load(type = "lakes", scale = "medium", category = 'physical',
                 returnclass = "sf",
                 destdir = paste0(getwd(), "./map-data/lakes")) # use this if already downloaded shapefiles
```

## 1. download SQLite databases for projects

This only needs to be done when first downloading the databases from Motus or if updating the data to download new detections, otherwise skip this step.

```{r}

# download/update project database and receiver databases (change to new = FALSE after first time downloading)
# takes several hours
tagme(projRecv = 47, new = FALSE, update = TRUE, forceMeta = TRUE, dir = "sql-databases/")
tagme(projRecv = 14, new = FALSE, update = TRUE, forceMeta = TRUE, dir = "sql-databases/")

```

## 2. load the detection data for tags

Connect to the SQLite databases and load the data we're interested in---detections of tags deployed by project 47. Join some tag metadata and receiver metadata to get all the information needed. Do a very small preliminary filter to get rid of obvious false detections. Save an RDS file of the detection data. This is essentially the raw data---it is not yet cleaned.

```{r}

# file path to sql database files
path <- "./sql-databases/"

#### pull out metadata for all project 47 tags #### 

# in the motus species list REKN = 4670
# double check species codes
sqldb <- tagme(projRecv = 47, new = FALSE, update = FALSE, dir = path)

sp.list <- c(4670) # red knot

species <- tbl(sqldb, "species") %>%
  filter(id %in% sp.list) %>%
  collect() %>%
  as.data.frame()

# list of motus projects (some tags were registered under project 14 - Loring)
projlist <- c(14, 47)

# get tag metadata
for (i in projlist){

  sqldb <- tagme(projRecv = i, new = FALSE, update = FALSE, dir = path)
  
  tagmet <- tbl(sqldb, "tagDeps")
  
  assign(paste0("m", i),
  tagmet %>%
    select(deployID, tagID, projectID, tsStart, tsEnd, deferSec, speciesID,
          markerNumber, latitude, longitude, fullID, comments) %>%
    filter(speciesID %in% sp.list) %>%
    collect() %>%
    as.data.frame() %>% # once in df format, can format dates with lubridate
    mutate(tsStart = as_datetime(tsStart, tz = "UTC", origin = "1970-01-01"),
           tsEnd = as_datetime(tsEnd, tz = "UTC", origin = "1970-01-01")))

}
rm(i)

tags.meta <- bind_rows(m14, m47) %>% 
  distinct() %>%
  filter(!is.na(longitude)) %>%
  mutate(markerNumber = str_remove(markerNumber, "-")) %>% # some band numbers still had a "-", most didn't, so removed for consistency and so would match with NJ tags of interest list
  group_by(tagID) %>%
  mutate(n = n()) %>%
  ungroup()

rm(m14, m47)

# get metadata for tags interested in (fall tags) and make sure metadata is all there
NJ.fall.tags <- read_csv("./misc-data/NJ_tags.csv")
NJ.fall.tags$markerNumber <- as.character(NJ.fall.tags$markerNumber)

NJ.tag.list <- NJ.fall.tags %>% 
  select(markerNumber) %>% 
  distinct() %>% 
  pull()

tags.meta <- tags.meta %>% 
  filter(markerNumber %in% NJ.tag.list)

# get ambiguous tag info
for (i in projlist){

  sqldb <- tagme(projRecv = i, new = FALSE, update = FALSE, dir = path)
  
  allambigs <- tbl(sqldb, "allambigs")
  
  assign(paste0("a", i),
    allambigs %>%
      collect() %>%
      as.data.frame())
}
rm(i)

ambig <- bind_rows(a14, a47)

rm(a14, a47)
  
# check if any tags interested in have ambiguous detections
tags.ambigs <- ambig %>% 
  group_by(ambigID) %>%
  mutate(inds = ifelse(any(motusTagID %in% tags.meta$tagID), "yes","no")) %>%
  filter(inds == "yes") %>%
  ungroup() %>%
  rename(tagID = motusTagID)

# get tag list (includes tags interested in and relevant ambiguous tags)
tag.list <- tags.meta %>%
  select(tagID) %>%
  bind_rows(., tags.ambigs %>% select(tagID)) %>%
  distinct() %>% pull()

# alltags dataset (~ 45 s to run 20-Jul-2020)
system.time({
  for (i in projlist){

    sqldb <- tagme(projRecv = i, new = FALSE, update = FALSE, dir = path)
    alltag <- tbl(sqldb, "alltags")
    assign(paste0("d", i),
           alltag %>%
             filter(tagProjID == i & motusTagID %in% tag.list) %>%
             select(hitID, runID, batchID, ts, sig, port, noise, freqsd, motusTagID,
                    ambigID, runLen, tagProjID, tagDeployID, tagDeployStart, tagDeployEnd,
                    tagDepLat, tagDepLon, deviceID, recvDeployID, recv,
                    speciesSci, markerNumber, mfgID) %>%
             collect() %>%
             as.data.frame() %>%
             mutate(ts = as_datetime(ts, tz = "UTC", origin = "1970-01-01"),
                    tagDeployStart = as_datetime(tagDeployStart, tz = "UTC", origin = "1970-01-01"),
                    tagDeployEnd = as_datetime(tagDeployEnd, tz = "UTC", origin = "1970-01-01")))
    
  }
  rm(i)
  
})

tags.detect <- bind_rows(d14, d47)

rm(d14, d47)

# get receiver metadata
# get tag metadata
for (i in projlist){
  
  sqldb <- tagme(projRecv = i, new = FALSE, update = FALSE, dir = path)
  
  recvmet <- tbl(sqldb, "recvDeps")
  
  assign(paste0("r", i), 
         recvmet %>%
           collect() %>%
           as.data.frame() %>% # once in df format, can format dates with lubridate
           mutate(tsStart = as_datetime(tsStart, tz = "UTC", origin = "1970-01-01"),
                  tsEnd = as_datetime(tsEnd, tz = "UTC", origin = "1970-01-01")))
  
}
rm(i)

recv.meta <- bind_rows(r14, r47) %>%
  rename(recvDeployID = deployID, recvProjectID = projectID) %>% 
  distinct() %>%
  filter(!is.na(longitude)) %>%
  group_by(deviceID) %>%
  mutate(n = n()) %>%
  ungroup()

rm(r14, r47)

recvs <- tags.detect %>%
  select(receiverID = recv, recvDeployID) %>%
  filter(!is.na(recvDeployID)) %>%
  distinct() %>% 
  left_join(., recv.meta) %>%
    select(receiverID, recvDeployID, recvProjectID, siteName,
           latitude, longitude, receiverType, tsStart, tsEnd, isMobile) %>%
  filter(!is.na(longitude))

# join recv metadata with detection data
tags.detect <-
  left_join(tags.detect, recvs %>%
              select(recv = receiverID, recvDeployID, receiverType, recvName = siteName,
                     recvLat = latitude, recvLon = longitude, isMobile, recvProjID = recvProjectID) %>%
              distinct())

# remove detections that occur outside of deployment time window or if no recv location
# add some useful variables
tags.detect <- tags.detect %>% 
  mutate(date = as.Date(ts),
         year = as.numeric(format(ts,'%Y')),
         month = as.numeric(format(ts,'%m'))) %>%
  filter(ts >= tagDeployStart & ts <= tagDeployEnd,
         !is.na(recvLat))

# determine if any ambiguous detections associated with tags we are interested in
tags.ambigs <- ambig %>% 
  group_by(ambigID) %>%
  mutate(inds = ifelse(any(motusTagID %in% tag.list), "yes","no")) %>%
  filter(inds == "yes") %>%
  distinct() %>%
  ungroup() %>%
  rename(tagID = motusTagID)

# 4 (of 82) ambiguous tags (5%) - remove from dataset, can examine more closely later if desired
# tag list (tags interested in with ambiguous tags removed)
tag.list <- tag.list %>% 
  as.data.frame() %>% 
  filter(!. %in% tags.ambigs$tagID) %>% 
  pull()

# filter detections to just birds interested in
tags.detect <- tags.detect %>%
  filter(motusTagID %in% tag.list)

# get motus filter results and add to dataframe
# get runs info
for (i in projlist){
  
  sqldb <- tagme(projRecv = i, new = FALSE, update = FALSE, dir = path)
  
  runs <- tbl(sqldb, "runs")
  
  assign(paste0("f", i), 
         runs %>%
           select(runID, motusFilter) %>%
           collect() %>%
           as.data.frame())
  
}
rm(i)

runs <- bind_rows(f14, f47)
rm(f14, f47)

# keep only runs associated with detection data
runs <- runs %>% 
  filter(runID %in% tags.detect$runID) %>%
  distinct()

# join runs with detection data
tags.detect <- left_join(tags.detect, runs)

# update filter 
# detections with freqsd > 0.1 (SG recvs only) --> these are generally false
tags.detect <- tags.detect %>% 
  mutate(motusFilter = ifelse(freqsd > 0.1, 0, motusFilter))

# filter out birds that have only detections that are likely false
tags.detect <- tags.detect %>%
  group_by(motusTagID) %>%
  mutate(af = sum(motusFilter)) %>%
  filter(af > 0) %>%
  ungroup() %>%
  select(-af)

# update list of tags after basic filter
tag.list <- tags.detect %>% 
  select(motusTagID) %>% 
  distinct() %>% pull()

# filter tag metadata to only tags remaining after basic filter
tags.meta <- tags.meta %>% 
  filter(tagID %in% tag.list)

# save data
saveRDS(tags.detect, file = "processed-data/NJ-tag-detections.rds")
write.csv(tags.detect, file = "processed-data/NJ-tag-detections.csv", row.names = FALSE)

saveRDS(tags.meta, file = "processed-data/NJ-tag-dep-metadata.rds")
write.csv(tags.meta, file = "processed-data/NJ-tag-dep-metadata.csv", row.names = FALSE)

```

## 3. data diagnostics and summaries

Do a basic filter to remove obvious false detections and make a map and signal strength plot for each bird to examine individually. Visualize movements detected and also spot other detections that may be false positives. I used the following protocol:

1. assign all detections where standard deviation of frequency offset >0.1 kHz `motusFilter = 0` because likely false (done above in section 2)
2. remove all birds that only have detections where `motusFilter = 0` (done above in section 2)
3. calculate proportion of detections where `motusFilter = 1` for each tag/receiver/day combination
4. remove all detections where proportion of detections that were likely true for that tag/receiver/day combination is less than half (this helps to remove false detections from particularly noisy towers)
5. create a map and signal strength plot for each bird and examine each individually

I suggest continuing to filter out potential false positives using the following criteria (this process is more subjective than the automated steps above):

6. identify and remove suspicious detections that meet one or more of the following criteria:
  + large movement at impossible flight speed
  + large movement in "wrong" direction and no detection curve pattern
  + isolated detection with relatively short run length (<10) and no clear detection pattern
  + detections of multiple birds at the same time at the same tower far from any other detections of those birds


```{r}

# load data ####
tags.detpro <- readRDS("processed-data/NJ-tag-detections.rds")
names(tags.detpro)

# 1. check for tags deployed more than once
dtag <- tags.detpro %>% select(motusTagID, tagDeployID) %>%
  distinct() %>%
  group_by(motusTagID) %>%
  mutate(n = n()) %>%
  ungroup()
any(dtag$n > 1)
# no tags deployed more than once so can use motusTagID as ID

# 2. examine all of the tags for additional false positives
str(tags.detpro)
summary(tags.detpro)

# calculate percent of detection classified as 'good' by the filter for each tag-recv-day combination
tags.detpro <- tags.detpro %>%
  group_by(date, recvName, motusTagID) %>%
  mutate(n = n(),
         ntrue = sum(motusFilter),
         ptrue = ntrue/n) %>%
  ungroup()

# list of unique motusTagIDs
nj.tagids <- tags.detpro %>% select(motusTagID) %>% arrange(motusTagID) %>% distinct() %>% pull()

# 3. filter out false positives
#### round 1 of filtering ####
# remove detections where less than half considered 'good' by filter for each tag-recv-day combination
nj.tags.filt <- tags.detpro %>%
  mutate(ftemp = ifelse(ptrue > 0.50, 1, 0),
         motusFilter = ftemp) %>%
  mutate(markerNumber = str_remove(markerNumber, "-")) %>% 
  filter(ftemp == 1)

# list of tags - 57 tags
nj.tags.filt.list <- nj.tags.filt %>%
  select(motusTagID) %>%
  arrange(motusTagID) %>%
  distinct() %>%
  pull()

# calculate site transitions
# check for birds with weird movements (e.g. too fast, 'wrong direction')
transit.check <- nj.tags.filt %>%
  do(add_deploy_loc(.)) %>%
  do(site_transit_min(.))

transit.check.suspect <- transit.check %>% 
  filter(suspect.transit == "suspect")
# seems like a false positive that got through filter - can remove later

# classify transitions as connected, or not_connected
tc <- transit.check %>%
  mutate(state = ifelse(dist.min == 0 | rate >= 5, "connected", "not_connected")) %>%
  filter(state == "connected") %>%
  select(motusTagID, ts.x, lat.x, lon.x, lat.y, lon.y)

# map filtered detections and save maps for each bird/tag as a png
# set limits to map based on locations of detections
# simplify detection data for plotting
nj.tags.path.filt <- fun.getpath(nj.tags.filt)

for (i in 1:length(nj.tags.filt.list)){
  
  bird <- nj.tags.path.filt %>% filter(motusTagID == nj.tags.filt.list[i])
  
  pbird <- tc %>% filter(motusTagID == nj.tags.filt.list[i]) %>%
    distinct()
  
  xmin <- min(bird$recvLon, bird$tagDepLon, na.rm = TRUE) - 2
  xmax <- max(bird$recvLon, bird$tagDepLon, na.rm = TRUE) + 2
  ymin <- min(bird$recvLat, bird$tagDepLat, na.rm = TRUE) - 1
  ymax <- max(bird$recvLat, bird$tagDepLat, na.rm = TRUE) + 1
  
  png(filename = paste0("figures/diagnostic-plots/nj-tags/round-1/",
                        bird$motusTagID,"-","map.png"),
      width=8, height=8, units="in", res=600)
  
  print(ggplot(data = world) +
          geom_sf() +
          geom_sf(data = lakes, fill = "white") +
          coord_sf(xlim = c(xmin, xmax), ylim = c(ymin, ymax), expand = FALSE) +
          geom_point(data = bird, aes(recvLon, recvLat, colour = month), alpha = 0.5, size = 5) +
          geom_segment(data = pbird, aes(x = lon.x, y = lat.x, xend = lon.y, yend = lat.y),
                       linetype = "dashed",
                       arrow = arrow(angle = 18, type = "closed", length = unit(0.1, "inches"))) +
          geom_point(data = bird,
                     aes(tagDepLon, tagDepLat), colour = "red",
                     shape = 8, size = 4) +
          scale_color_gradientn(colors = rev(viridis_pal()(12)), limits = c(1,12)) +
          ggtitle(paste0("motusTagID: ", bird$motusTagID[1])))
  dev.off()
  
}
rm(i)

# make sigs strength plots
for (i in 1:length(nj.tags.filt.list)){
  
  png(filename = paste0("figures/diagnostic-plots/nj-tags/round-1/", "sigstrength-",
                        nj.tags.filt.list[i],".png"),
      width=11, height=7.5, units="in", res=600)
  print(plotTagSig_mod(nj.tags.filt, motusTagID = nj.tags.filt.list[i]))
  dev.off()
}
rm(i)

# write csv to keep track of issues spotted via visual inspection
write.csv(nj.tags.filt %>% select(motusTagID, markerNumber) %>% distinct() %>% arrange(motusTagID),
          file = "./processed-data/filtering_notes_tags_round1.csv", row.names=FALSE)

# write rds and csv files of detection data after the basic filter has been run
write.csv(nj.tags.filt, file = "./processed-data/NJ-tag-detections-semiclean.csv", row.names = FALSE)
saveRDS(nj.tags.filt, file = "./processed-data/NJ-tag-detections-semiclean.rds")

```

**Comment by leberrigan** [comment]
This has turned into quite the discussion - moved!
